In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_val_score

In [4]:
X_old=pd.read_csv("preprocessorInput.txt", sep='\t')
X_old.head()

eid  class  age  sex  array      pc1      pc2       pc3       pc4  \
0  2173321      1   61    0      1 -12.1787  2.63696  0.203519  4.625490   
1  4979768      1   59    1      1 -10.9307  3.10202 -0.447919  0.197328   
2  4111782      1   52    1      1 -13.7279  3.71157 -2.816260 -2.594760   
3  2059130      1   54    1      1 -12.4505  4.29629 -0.395055 -0.659687   
4  3484756      1   62    0      1 -11.5569  3.66607 -0.117154  1.045210   

        pc5  ...  rs17042102  rs4135240  rs55730499  rs140570886  rs1556516  \
0  11.26250  ...         0.0        1.0         0.0          0.0        1.0   
1  -2.20478  ...         0.0        2.0         0.0          0.0        0.0   
2  -4.55278  ...         0.0        0.0         0.0          0.0        1.0   
3   0.05068  ...         0.0        0.0         0.0          0.0        1.0   
4  -7.18600  ...         0.0        1.0         1.0          0.0        1.0   

   rs600038  rs4746140  rs17617337  rs4766578  rs56094641  
0       0.0        1.0         1.0        0.0         0.0  
1       0.0        0.0         0.0        1.0         0.0  
2       0.0        0.0         1.0        1.0         0.0  
3       1.0        0.0         0.0        2.0         0.0  
4       0.0        1.0         2.0        2.0         2.0  

[5 rows x 26 columns]

In [5]:
X=pd.read_csv("test.txt", sep='\t')
X.head()

eid  class  array      pc1      pc2       pc3       pc4       pc5  \
0  2173321      1      1 -12.1787  2.63696  0.203519  4.625490  11.26250   
1  4979768      1      1 -10.9307  3.10202 -0.447919  0.197328  -2.20478   
2  4111782      1      1 -13.7279  3.71157 -2.816260 -2.594760  -4.55278   
3  2059130      1      1 -12.4505  4.29629 -0.395055 -0.659687   0.05068   
4  3484756      1      1 -11.5569  3.66607 -0.117154  1.045210  -7.18600   

        pc6       pc7  ...  indicator_1    adjY_1  indicator_2    adjY_2  \
0 -1.091930 -0.798969  ...            0  0.568200            1  0.567780   
1  1.093750  0.130705  ...            0  0.435824            0  0.423497   
2  0.884419  1.212450  ...            0  0.639138            0  0.639365   
3 -1.036610  0.582252  ...            0  0.555871            0  0.573545   
4 -1.953130  1.957360  ...            1  0.560715            0  0.572816   

   indicator_3    adjY_3  indicator_4    adjY_4  indicator_5    adjY_5  
0            0  0.578435            0  0.564814            0  0.581280  
1            0  0.417933            0  0.434874            0  0.416811  
2            0  0.629162            1  0.640186            1  0.635849  
3            0  0.545321            0  0.564933            0  0.556822  
4            0  0.585846            0  0.567582            0  0.584692  

[5 rows x 34 columns]

In [6]:
y = X['class'] # useless
X.drop('class', axis=1, inplace=True)
X.head()

eid  array      pc1      pc2       pc3       pc4       pc5       pc6  \
0  2173321      1 -12.1787  2.63696  0.203519  4.625490  11.26250 -1.091930   
1  4979768      1 -10.9307  3.10202 -0.447919  0.197328  -2.20478  1.093750   
2  4111782      1 -13.7279  3.71157 -2.816260 -2.594760  -4.55278  0.884419   
3  2059130      1 -12.4505  4.29629 -0.395055 -0.659687   0.05068 -1.036610   
4  3484756      1 -11.5569  3.66607 -0.117154  1.045210  -7.18600 -1.953130   

        pc7      pc8  ...  indicator_1    adjY_1  indicator_2    adjY_2  \
0 -0.798969 -2.10674  ...            0  0.568200            1  0.567780   
1  0.130705  2.76544  ...            0  0.435824            0  0.423497   
2  1.212450 -1.92885  ...            0  0.639138            0  0.639365   
3  0.582252  1.87808  ...            0  0.555871            0  0.573545   
4  1.957360 -4.92783  ...            1  0.560715            0  0.572816   

   indicator_3    adjY_3  indicator_4    adjY_4  indicator_5    adjY_5  
0            0  0.578435            0  0.564814            0  0.581280  
1            0  0.417933            0  0.434874            0  0.416811  
2            0  0.629162            1  0.640186            1  0.635849  
3            0  0.545321            0  0.564933            0  0.556822  
4            0  0.585846            0  0.567582            0  0.584692  

[5 rows x 33 columns]

In [7]:
from tpot.builtins.resAdjPredefinedSplits import resAdjPredefinedSplits
from tpot.builtins.resAdjScorers import resAdjMseScorer
from tpot.builtins.resAdjGradientBoostingRegressor import resAdjGradientBoostingRegressor


In [8]:
s = resAdjPredefinedSplits(n_splits=5)
cv_split = s.split(X,y)

In [9]:
for train, test in cv_split:
    print(train)
    print(test)

[    0     1     2 ... 13673 13674 13675]
[    4    12    18 ... 13662 13666 13668]
[    1     2     3 ... 13670 13673 13675]
[    0     5     8 ... 13671 13672 13674]
[    0     1     2 ... 13673 13674 13675]
[    6    17    20 ... 13653 13659 13668]
[    0     1     3 ... 13672 13674 13675]
[    2     6     9 ... 13664 13665 13673]
[    0     1     3 ... 13673 13674 13675]
[    2     7     8 ... 13654 13665 13666]


In [10]:
est = resAdjGradientBoostingRegressor(random_state=42)
cv_scores = cross_val_score(est, X, y, scoring=resAdjMseScorer, cv=resAdjPredefinedSplits(n_splits=5), error_score='raise')
cv_scores

array([-0.22405776, -0.22234846, -0.22688721, -0.22053962, -0.21841295])

In [11]:
# should provide same results with diff y since y is not useful
est = resAdjGradientBoostingRegressor(random_state=42)
cv_scores = cross_val_score(est, X, X['array'], scoring=resAdjMseScorer, cv=resAdjPredefinedSplits(n_splits=5))
cv_scores

array([-0.22405776, -0.22234846, -0.22688721, -0.22053962, -0.21841295])

In [12]:
# test resAdjTransformer
from tpot.builtins.resAdjTransformer import resAdjTransformer
C_list = ['pc1', 
         'pc2', 
         'pc3', 
         'pc4', 
         'pc5', 
         'pc6', 
         'pc7', 
         'pc8', 
         'pc9', 
         'pc10']
trans = resAdjTransformer(C=C_list, adj_list='covar_feature.csv')
trans.fit(X, y)
X_adj = trans.transform(X)

In [13]:
X_adj.head() # 0, 1 is adjusted columns

0         1      eid  array  rs4135240  rs55730499  rs140570886  \
0  0.440358 -0.205527  2173321      1        1.0         0.0          0.0   
1  0.423599 -0.218604  4979768      1        2.0         0.0          0.0   
2  0.408609 -0.218157  4111782      1        0.0         0.0          0.0   
3  0.417041 -0.207989  2059130      1        0.0         0.0          0.0   
4  0.425590 -0.205368  3484756      1        1.0         1.0          0.0   

   rs1556516  rs600038  rs4746140  ...  indicator_1    adjY_1  indicator_2  \
0        1.0       0.0        1.0  ...            0  0.568200            1   
1        0.0       0.0        0.0  ...            0  0.435824            0   
2        1.0       0.0        0.0  ...            0  0.639138            0   
3        1.0       1.0        0.0  ...            0  0.555871            0   
4        1.0       0.0        1.0  ...            1  0.560715            0   

     adjY_2  indicator_3    adjY_3  indicator_4    adjY_4  indicator_5  \
0  0.567780            0  0.578435            0  0.564814            0   
1  0.423497            0  0.417933            0  0.434874            0   
2  0.639365            0  0.629162            1  0.640186            1   
3  0.573545            0  0.545321            0  0.564933            0   
4  0.572816            0  0.585846            0  0.567582            0   

     adjY_5  
0  0.581280  
1  0.416811  
2  0.635849  
3  0.556822  
4  0.584692  

[5 rows x 23 columns]