In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_val_score

In [4]:
X=pd.read_csv("testingData/basicTest/HF_train.txt", sep='\t')
X.head()

eid  array      pc1      pc2       pc3       pc4       pc5       pc6  \
0  2173321      1 -12.1787  2.63696  0.203519  4.625490  11.26250 -1.091930   
1  4979768      1 -10.9307  3.10202 -0.447919  0.197328  -2.20478  1.093750   
2  4111782      1 -13.7279  3.71157 -2.816260 -2.594760  -4.55278  0.884419   
3  2059130      1 -12.4505  4.29629 -0.395055 -0.659687   0.05068 -1.036610   
4  3484756      1 -11.5569  3.66607 -0.117154  1.045210  -7.18600 -1.953130   

        pc7      pc8  ...  indicator_1    adjY_1  indicator_2    adjY_2  \
0 -0.798969 -2.10674  ...            1  0.567780            0  0.578435   
1  0.130705  2.76544  ...            0  0.423497            0  0.417933   
2  1.212450 -1.92885  ...            0  0.639365            0  0.629162   
3  0.582252  1.87808  ...            0  0.573545            0  0.545321   
4  1.957360 -4.92783  ...            0  0.572816            0  0.585846   

   indicator_3    adjY_3  indicator_4    adjY_4  indicator_5    adjY_5  
0            0  0.564814            0  0.581280            1  0.572122  
1            0  0.434874            0  0.416811            0  0.433987  
2            1  0.640186            1  0.635849            0  0.644544  
3            0  0.564933            0  0.556822            1  0.563987  
4            0  0.567582            0  0.584692            0  0.586635  

[5 rows x 34 columns]

In [5]:
X.columns

Index(['eid', 'array', 'pc1', 'pc2', 'pc3', 'pc4', 'pc5', 'pc6', 'pc7', 'pc8',
       'pc9', 'pc10', 'rs660240', 'rs17042102', 'rs4135240', 'rs55730499',
       'rs140570886', 'rs1556516', 'rs600038', 'rs4746140', 'rs17617337',
       'rs4766578', 'rs56094641', 'adjY', 'indicator_1', 'adjY_1',
       'indicator_2', 'adjY_2', 'indicator_3', 'adjY_3', 'indicator_4',
       'adjY_4', 'indicator_5', 'adjY_5'],
      dtype='object')

In [6]:
y = X['adjY'] 
X.drop('adjY', axis=1, inplace=True)
X.head()

eid  array      pc1      pc2       pc3       pc4       pc5       pc6  \
0  2173321      1 -12.1787  2.63696  0.203519  4.625490  11.26250 -1.091930   
1  4979768      1 -10.9307  3.10202 -0.447919  0.197328  -2.20478  1.093750   
2  4111782      1 -13.7279  3.71157 -2.816260 -2.594760  -4.55278  0.884419   
3  2059130      1 -12.4505  4.29629 -0.395055 -0.659687   0.05068 -1.036610   
4  3484756      1 -11.5569  3.66607 -0.117154  1.045210  -7.18600 -1.953130   

        pc7      pc8  ...  indicator_1    adjY_1  indicator_2    adjY_2  \
0 -0.798969 -2.10674  ...            1  0.567780            0  0.578435   
1  0.130705  2.76544  ...            0  0.423497            0  0.417933   
2  1.212450 -1.92885  ...            0  0.639365            0  0.629162   
3  0.582252  1.87808  ...            0  0.573545            0  0.545321   
4  1.957360 -4.92783  ...            0  0.572816            0  0.585846   

   indicator_3    adjY_3  indicator_4    adjY_4  indicator_5    adjY_5  
0            0  0.564814            0  0.581280            1  0.572122  
1            0  0.434874            0  0.416811            0  0.433987  
2            1  0.640186            1  0.635849            0  0.644544  
3            0  0.564933            0  0.556822            1  0.563987  
4            0  0.567582            0  0.584692            0  0.586635  

[5 rows x 33 columns]

In [7]:
# test import from tpot builtins

from glob import glob
for file in glob('tpot/builtins/resAdj_selectors/res*py'):
    print(file)

tpot/builtins/resAdj_selectors/resAdjVarianceThreshold.py
tpot/builtins/resAdj_selectors/resAdjSelectFwe.py
tpot/builtins/resAdj_selectors/resAdjSelectPercentile.py
tpot/builtins/resAdj_selectors/resAdjSelectFromModel.py


In [8]:
# test import selectors
for file in glob('tpot/builtins/resAdj_selectors/res*py'):
    opname = file.split('/')[-1].split('.')[0]
    print('test import', opname)
    # import as string
    exec('from tpot.builtins import {}'.format(opname))

test import resAdjVarianceThreshold
test import resAdjSelectFwe
test import resAdjSelectPercentile
test import resAdjSelectFromModel


In [9]:
# test import preprocessors
for file in glob('tpot/builtins/resAdj_preprocessors/res*py'):
    opname = file.split('/')[-1].split('.')[0]
    print('test import', opname)
    # import as string
    exec('from tpot.builtins import {}'.format(opname))

test import resAdjNormalizer
test import resAdjStandardScaler
test import resAdjOneHotEncoder
test import resAdjPolynomialFeatures
test import resAdjRBFSampler
test import resAdjFeatureAgglomeration
test import resAdjMinMaxScaler
test import resAdjBinarizer
test import resAdjMaxAbsScaler
test import resAdjPCA
test import resAdjNystroem
test import resAdjFastICA
test import resAdjRobustScaler
test import resAdjZeroCount


In [10]:
# test import estimators
for file in glob('tpot/builtins/resAdj_estimators/res*py'):
    opname = file.split('/')[-1].split('.')[0]
    print('test import', opname)
    # import as string
    exec('from tpot.builtins import {}'.format(opname))

test import resAdjRandomForestRegressor
test import resAdjLinearSVR
test import resAdjGradientBoostingRegressor
test import resAdjExtraTreesRegressor
test import resAdjDecisionTreeRegressor
test import resAdjSGDRegressor
test import resAdjAdaBoostRegressor
test import resAdjLassoLarsCV
test import resAdjXGBRegressor
test import resAdjElasticNetCV
test import resAdjRidgeCV
test import resAdjKNeighborsRegressor


In [11]:
# test import scorer
from tpot.builtins import resAdjPredefinedSplits
from tpot.builtins import resAdjMseScorer



In [12]:
s = resAdjPredefinedSplits(n_splits=5)
cv_split = s.split(X,y)

In [13]:
for train, test in cv_split:
    print(train)
    print(test)

[    1     2     3 ... 13670 13673 13675]
[    0     5     8 ... 13671 13672 13674]
[    0     1     2 ... 13673 13674 13675]
[    6    17    20 ... 13653 13659 13668]
[    0     1     3 ... 13672 13674 13675]
[    2     6     9 ... 13664 13665 13673]
[    0     1     3 ... 13673 13674 13675]
[    2     7     8 ... 13654 13665 13666]
[    1     2     4 ... 13673 13674 13675]
[    0     3     5 ... 13662 13668 13671]


In [14]:
# test resAdjTransformer
from tpot.builtins import resAdjTransformer
C_list = ['pc1', 
         'pc2', 
         'pc3', 
         'pc4', 
         'pc5', 
         'pc6', 
         'pc7', 
         'pc8', 
         'pc9', 
         'pc10']
trans = resAdjTransformer(C=C_list, adj_list='testingData/basicTest/adj_list.csv')
trans.fit(X, y)
X_adj = trans.transform(X)

In [15]:
X_adj.head() # 0, 1 is adjusted columns

0         1         2         3         4         5         6  \
0  0.452480 -0.210460  0.422969 -0.190018 -0.016305 -0.028530 -0.357644   
1  0.433118 -0.219887  1.377390 -0.160989 -0.019874 -1.016256 -0.457167   
2  0.401787 -0.229240 -0.615533 -0.165076 -0.017248 -0.006409 -0.426864   
3  0.437802 -0.213537 -0.637834 -0.168728 -0.016379 -0.042997  0.561582   
4  0.419356 -0.204275  0.424931  0.804538 -0.016176  0.019699 -0.443135   

          7         8         9  ...  indicator_1    adjY_1  indicator_2  \
0  0.704947  0.589847 -0.988665  ...            1  0.567780            0   
1 -0.300463 -0.376296  0.009962  ...            0  0.423497            0   
2 -0.267236  0.608227 -0.007376  ...            0  0.639365            0   
3 -0.296374 -0.383996  1.017269  ...            0  0.573545            0   
4  0.726770  1.609082  0.995223  ...            0  0.572816            0   

     adjY_2  indicator_3    adjY_3  indicator_4    adjY_4  indicator_5  \
0  0.578435            0  0.564814            0  0.581280            1   
1  0.417933            0  0.434874            0  0.416811            0   
2  0.629162            1  0.640186            1  0.635849            0   
3  0.545321            0  0.564933            0  0.556822            1   
4  0.585846            0  0.567582            0  0.584692            0   

     adjY_5  
0  0.572122  
1  0.433987  
2  0.644544  
3  0.563987  
4  0.586635  

[5 rows x 23 columns]

In [16]:
X_adj.shape

(13676, 23)

In [17]:
indicators = X_adj.filter(regex='indicator').columns
indicators

Index(['indicator_1', 'indicator_2', 'indicator_3', 'indicator_4',
       'indicator_5'],
      dtype='object')

In [18]:
adjys = X_adj.filter(regex='adjY').columns
adjys

Index(['adjY_1', 'adjY_2', 'adjY_3', 'adjY_4', 'adjY_5'], dtype='object')

In [19]:
# test all preprocessors can ignore adjY and indicators
# test it in a pipeline
from sklearn.pipeline import make_pipeline
reg = resAdjDecisionTreeRegressor(random_state=42)
for file in glob('tpot/builtins/resAdj_preprocessors/res*py'):
    
    opname = file.split('/')[-1].split('.')[0]
    print('test selection with', opname)
    sel = eval(opname)()
    if hasattr(sel, 'random_state'):
        sel.set_params(random_state=42)
    print(sel)
    est = make_pipeline(sel, reg)
    cv_scores_1 = cross_val_score(est, X, y.values, scoring=resAdjMseScorer, cv=resAdjPredefinedSplits(n_splits=5), error_score='raise')
    cv_scores_2 = cross_val_score(est, X, X['array'].values, scoring=resAdjMseScorer, cv=resAdjPredefinedSplits(n_splits=5))
    if np.array_equal(cv_scores_1, cv_scores_2):
        print('{} passed'.format(opname))
    else:
        print('{} failed'.format(opname))
        break

test selection with resAdjNormalizer
resAdjNormalizer(norm='l2')
resAdjNormalizer passed
test selection with resAdjStandardScaler
resAdjStandardScaler(copy=True)
resAdjStandardScaler passed
test selection with resAdjOneHotEncoder
resAdjOneHotEncoder(minimum_fraction=0.05, sparse=False, threshold=10)
resAdjOneHotEncoder passed
test selection with resAdjPolynomialFeatures
resAdjPolynomialFeatures(degree=2, include_bias=False, interaction_only=False)
resAdjPolynomialFeatures passed
test selection with resAdjRBFSampler
resAdjRBFSampler(gamma=1.01, random_state=42)
resAdjRBFSampler passed
test selection with resAdjFeatureAgglomeration
resAdjFeatureAgglomeration(affinity='euclidean', linkage='ward')
resAdjFeatureAgglomeration passed
test selection with resAdjMinMaxScaler
resAdjMinMaxScaler(copy=True)
resAdjMinMaxScaler passed
test selection with resAdjBinarizer
resAdjBinarizer(threshold=0.0)
resAdjBinarizer passed
test selection with resAdjMaxAbsScaler
resAdjMaxAbsScaler(copy=True)
resAdjMax

/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/decomposition/_fastica.py:119: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  ConvergenceWarning)
/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/decomposition/_fastica.py:119: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  ConvergenceWarning)
/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/decomposition/_fastica.py:119: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  ConvergenceWarning)
/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/decomposition/_fastica.py:119: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  ConvergenceWarning)
/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/decomposition/_fastica.py:

resAdjFastICA passed
test selection with resAdjRobustScaler
resAdjRobustScaler(copy=True)
resAdjRobustScaler passed
test selection with resAdjZeroCount
resAdjZeroCount()
resAdjZeroCount passed


In [20]:
# test it alone
for file in glob('tpot/builtins/resAdj_preprocessors/res*py'):
    
    opname = file.split('/')[-1].split('.')[0]
    print('test selection with', opname)
    sel = eval(opname)()
    if hasattr(sel, 'random_state'):
        sel.set_params(random_state=42)
    print(sel)
    s = resAdjPredefinedSplits(n_splits=5)
    cv_split = s.split(X,y)
    for train, test in cv_split:
        sel.fit(X.loc[train, :], y.loc[train])
        X_sel = sel.transform(X.loc[train, :])
        inds = X_sel.filter(regex='indicator').columns
        ays = X_adj.filter(regex='adjY').columns
        if np.array_equal(inds, indicators) and np.array_equal(adjys, ays):
            print('{} passed'.format(opname))
            break
        else:
            print('{} failed'.format(opname))
            break

test selection with resAdjNormalizer
resAdjNormalizer(norm='l2')
resAdjNormalizer passed
test selection with resAdjStandardScaler
resAdjStandardScaler(copy=True)
resAdjStandardScaler passed
test selection with resAdjOneHotEncoder
resAdjOneHotEncoder(minimum_fraction=0.05, sparse=False, threshold=10)
resAdjOneHotEncoder passed
test selection with resAdjPolynomialFeatures
resAdjPolynomialFeatures(degree=2, include_bias=False, interaction_only=False)
resAdjPolynomialFeatures passed
test selection with resAdjRBFSampler
resAdjRBFSampler(gamma=1.01, random_state=42)
resAdjRBFSampler passed
test selection with resAdjFeatureAgglomeration
resAdjFeatureAgglomeration(affinity='euclidean', linkage='ward')
resAdjFeatureAgglomeration passed
test selection with resAdjMinMaxScaler
resAdjMinMaxScaler(copy=True)
resAdjMinMaxScaler passed
test selection with resAdjBinarizer
resAdjBinarizer(threshold=0.0)
resAdjBinarizer passed
test selection with resAdjMaxAbsScaler
resAdjMaxAbsScaler(copy=True)
resAdjMax

/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/decomposition/_fastica.py:119: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  ConvergenceWarning)


In [21]:
# test all selector can ignore adjY and indicators
# test it in a pipeline
from sklearn.pipeline import make_pipeline
reg = resAdjDecisionTreeRegressor(random_state=42)
for file in glob('tpot/builtins/resAdj_selectors/res*py'):
    
    opname = file.split('/')[-1].split('.')[0]
    print('test selection with', opname)
    sel = eval(opname)()
    if hasattr(sel, 'random_state'):
        sel.set_params(random_state=42)
    print(sel)
    est = make_pipeline(sel, reg)
    cv_scores_1 = cross_val_score(est, X, y.values, scoring=resAdjMseScorer, cv=resAdjPredefinedSplits(n_splits=5), error_score='raise')
    cv_scores_2 = cross_val_score(est, X, X['array'].values, scoring=resAdjMseScorer, cv=resAdjPredefinedSplits(n_splits=5))
    if np.array_equal(cv_scores_1, cv_scores_2):
        print('{} passed'.format(opname))
    else:
        print('{} failed'.format(opname))
        break

test selection with resAdjVarianceThreshold
resAdjVarianceThreshold(threshold=0.0)
resAdjVarianceThreshold passed
test selection with resAdjSelectFwe
resAdjSelectFwe(alpha=0.05, score_func=<function f_regression at 0x1a1f54c0d0>)
resAdjSelectFwe passed
test selection with resAdjSelectPercentile
resAdjSelectPercentile(percentile=10,
                       score_func=<function f_regression at 0x1a1f54c0d0>)
resAdjSelectPercentile passed
test selection with resAdjSelectFromModel
resAdjSelectFromModel(estimator=ExtraTreesRegressor(bootstrap=False,
                                                    ccp_alpha=0.0,
                                                    criterion='mse',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                              

In [22]:
# test it alone
for file in glob('tpot/builtins/resAdj_selectors/res*py'):
    
    opname = file.split('/')[-1].split('.')[0]
    print('test selection with', opname)
    sel = eval(opname)()
    if hasattr(sel, 'random_state'):
        sel.set_params(random_state=42)
    print(sel)
    s = resAdjPredefinedSplits(n_splits=5)
    cv_split = s.split(X,y)
    for train, test in cv_split:
        sel.fit(X.loc[train, :], y.loc[train])
        X_sel = sel.transform(X.loc[train, :])
        inds = X_sel.filter(regex='indicator').columns
        ays = X_adj.filter(regex='adjY').columns
        if np.array_equal(inds, indicators) and np.array_equal(adjys, ays):
            print('{} passed'.format(opname))
            break
        else:
            print('{} failed'.format(opname))
            break

test selection with resAdjVarianceThreshold
resAdjVarianceThreshold(threshold=0.0)
resAdjVarianceThreshold passed
test selection with resAdjSelectFwe
resAdjSelectFwe(alpha=0.05, score_func=<function f_regression at 0x1a1f54c0d0>)
resAdjSelectFwe passed
test selection with resAdjSelectPercentile
resAdjSelectPercentile(percentile=10,
                       score_func=<function f_regression at 0x1a1f54c0d0>)
resAdjSelectPercentile passed
test selection with resAdjSelectFromModel
resAdjSelectFromModel(estimator=ExtraTreesRegressor(bootstrap=False,
                                                    ccp_alpha=0.0,
                                                    criterion='mse',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                              

In [23]:
# test all estimators can ignore y to return the same cv scores

for file in glob('tpot/builtins/resAdj_estimators/res*py'):
    opname = file.split('/')[-1].split('.')[0]
    print('test cv scores from ', opname)
    est = eval(opname)()
    if hasattr(est, 'random_state'):
        est.set_params(random_state=42)
    if hasattr(est, 'n_estimators'):
        est.set_params(n_estimators=20) # for a quick test
    print(est)
    cv_scores_1 = cross_val_score(est, X, y.values, scoring=resAdjMseScorer, cv=resAdjPredefinedSplits(n_splits=5), error_score='raise')
    cv_scores_2 = cross_val_score(est, X, X['array'].values, scoring=resAdjMseScorer, cv=resAdjPredefinedSplits(n_splits=5))
    if np.array_equal(cv_scores_1, cv_scores_2):
        print('{} passed'.format(opname))
    else:
        print('{} failed'.format(opname))
        break

test cv scores from  resAdjRandomForestRegressor
resAdjRandomForestRegressor(bootstrap=True, max_features='auto',
                            min_samples_leaf=1, min_samples_split=2,
                            n_estimators=20, random_state=42)
resAdjRandomForestRegressor passed
test cv scores from  resAdjLinearSVR
resAdjLinearSVR(C=1.0, dual=True, epsilon=0.0, loss='epsilon_insensitive',
                random_state=42, tol=0.0001)


/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increa

resAdjLinearSVR passed
test cv scores from  resAdjGradientBoostingRegressor
resAdjGradientBoostingRegressor(alpha=0.9, learning_rate=0.1, loss='ls',
                                max_depth=3, max_features=None,
                                min_samples_leaf=1, min_samples_split=2,
                                n_estimators=20, random_state=42,
                                subsample=0.05)
resAdjGradientBoostingRegressor passed
test cv scores from  resAdjExtraTreesRegressor
resAdjExtraTreesRegressor(bootstrap=None, max_features='auto',
                          min_samples_leaf=1, min_samples_split=2,
                          n_estimators=20, random_state=42)


/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)
/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)
/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)
/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously

resAdjExtraTreesRegressor passed
test cv scores from  resAdjDecisionTreeRegressor
resAdjDecisionTreeRegressor(max_depth=None, min_samples_leaf=1,
                            min_samples_split=2, random_state=42)
resAdjDecisionTreeRegressor passed
test cv scores from  resAdjSGDRegressor
resAdjSGDRegressor(alpha=0.001, eta0=0.01, fit_intercept=True, l1_ratio=0.25,
                   learning_rate='invscaling', loss='squared_loss',
                   penalty='elasticnet', power_t=0.5, random_state=42)
resAdjSGDRegressor passed
test cv scores from  resAdjAdaBoostRegressor
resAdjAdaBoostRegressor(learning_rate=1.0, loss='linear', n_estimators=20,
                        random_state=42)
resAdjAdaBoostRegressor passed
test cv scores from  resAdjLassoLarsCV
resAdjLassoLarsCV(normalize=True)
resAdjLassoLarsCV passed
test cv scores from  resAdjXGBRegressor
resAdjXGBRegressor(learning_rate=0.1, max_depth=3, min_child_weight=2,
                   n_estimators=20, nthread=1, objective='reg:squared

In [24]:
# test all selector can ignore adjY and indicators
# test it in a pipeline
# 3 step pipeline
from sklearn.pipeline import make_pipeline
reg = resAdjDecisionTreeRegressor(random_state=42)
trans = resAdjTransformer(C=C_list, adj_list='testingData/basicTest/adj_list.csv')
for file in glob('tpot/builtins/resAdj_selectors/res*py'):
    
    opname = file.split('/')[-1].split('.')[0]
    print('test selection with', opname)
    sel = eval(opname)()
    if hasattr(sel, 'random_state'):
        sel.set_params(random_state=42)
    print(sel)
    est = make_pipeline(trans, sel, reg)
    cv_scores_1 = cross_val_score(est, X, y.values, scoring=resAdjMseScorer, cv=resAdjPredefinedSplits(n_splits=5), error_score='raise')
    cv_scores_2 = cross_val_score(est, X, X['array'].values, scoring=resAdjMseScorer, cv=resAdjPredefinedSplits(n_splits=5))
    if np.array_equal(cv_scores_1, cv_scores_2):
        est.fit(X, y)
        scores = est.score(X, y)
        print('{} passed'.format(opname))
    else:
        print('{} failed'.format(opname))
        break

test selection with resAdjVarianceThreshold
resAdjVarianceThreshold(threshold=0.0)
resAdjVarianceThreshold passed
test selection with resAdjSelectFwe
resAdjSelectFwe(alpha=0.05, score_func=<function f_regression at 0x1a1f54c0d0>)
resAdjSelectFwe passed
test selection with resAdjSelectPercentile
resAdjSelectPercentile(percentile=10,
                       score_func=<function f_regression at 0x1a1f54c0d0>)
resAdjSelectPercentile passed
test selection with resAdjSelectFromModel
resAdjSelectFromModel(estimator=ExtraTreesRegressor(bootstrap=False,
                                                    ccp_alpha=0.0,
                                                    criterion='mse',
                                                    max_depth=None,
                                                    max_features='auto',
                                                    max_leaf_nodes=None,
                                                    max_samples=None,
                              

In [26]:
reg = resAdjDecisionTreeRegressor(random_state=42)
trans = resAdjTransformer(C=C_list, adj_list='testingData/basicTest/adj_list.csv')
for file in glob('tpot/builtins/resAdj_preprocessors/res*py'):
    
    opname = file.split('/')[-1].split('.')[0]
    print('test transformation with', opname)
    sel = eval(opname)()
    if hasattr(sel, 'random_state'):
        sel.set_params(random_state=42)
    print(sel)
    est = make_pipeline(trans, sel, reg)
    cv_scores_1 = cross_val_score(est, X, y.values, scoring=resAdjMseScorer, cv=resAdjPredefinedSplits(n_splits=5), error_score='raise')
    cv_scores_2 = cross_val_score(est, X, X['array'].values, scoring=resAdjMseScorer, cv=resAdjPredefinedSplits(n_splits=5))
    if np.array_equal(cv_scores_1, cv_scores_2):
        est.fit(X, y)
        scores = est.score(X, y)
        print('{} passed'.format(opname))
    else:
        print('{} failed'.format(opname))
        break

test transformation with resAdjNormalizer
resAdjNormalizer(norm='l2')
resAdjNormalizer passed
test transformation with resAdjStandardScaler
resAdjStandardScaler(copy=True)
resAdjStandardScaler passed
test transformation with resAdjOneHotEncoder
resAdjOneHotEncoder(minimum_fraction=0.05, sparse=False, threshold=10)
resAdjOneHotEncoder passed
test transformation with resAdjPolynomialFeatures
resAdjPolynomialFeatures(degree=2, include_bias=False, interaction_only=False)
resAdjPolynomialFeatures passed
test transformation with resAdjRBFSampler
resAdjRBFSampler(gamma=1.01, random_state=42)
resAdjRBFSampler passed
test transformation with resAdjFeatureAgglomeration
resAdjFeatureAgglomeration(affinity='euclidean', linkage='ward')
resAdjFeatureAgglomeration passed
test transformation with resAdjMinMaxScaler
resAdjMinMaxScaler(copy=True)
resAdjMinMaxScaler passed
test transformation with resAdjBinarizer
resAdjBinarizer(threshold=0.0)
resAdjBinarizer passed
test transformation with resAdjMaxAbsS

/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/decomposition/_fastica.py:119: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  ConvergenceWarning)
/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/decomposition/_fastica.py:119: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  ConvergenceWarning)
/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/decomposition/_fastica.py:119: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  ConvergenceWarning)
/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/decomposition/_fastica.py:119: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  ConvergenceWarning)
/Users/weixuanf/anaconda3/lib/python3.7/site-packages/sklearn/decomposition/_fastica.py:

resAdjFastICA passed
test transformation with resAdjRobustScaler
resAdjRobustScaler(copy=True)
resAdjRobustScaler passed
test transformation with resAdjZeroCount
resAdjZeroCount()
resAdjZeroCount passed
